# Uncomment this line to define a global platform for your project
platform :ios, '12.0'

CONFIG = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
unless File.exist?(CONFIG)
  raise "#{CONFIG} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
end

require File.expand_path(File.join('..', 'Flutter', 'podhelper.rb'), CONFIG)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
